// enums
export const alterator = {
  TELEPORTER_IN: 'TELEPORTER_IN',
  TELEPORTER_OUT: 'TELEPORTER_OUT',
  TRAP: 'TRAP',
  DIRECTIONER_UPWARDS: 'DIRECTIONER_UPWARDS',
  DIRECTIONER_DOWNWARDS: 'DIRECTIONER_DOWNWARDS',
  DIRECTIONER_RIGHT: 'DIRECTIONER_RIGHT',
  DIRECTIONER_LEFT: 'DIRECTIONER_LEFT'
}

export const modifier = {
  KILLER: 'KILLER',
  MULTIPLIER: 'MULTIPLIER',
  MOUNTAIN_RANGE: 'MOUNTAIN_RANGE'
}

export const team = {
  BLUE: 'BLUE',
  GREEN: 'GREEN'
}

export const gameStatus = {
  STARTED: 'STARTED',
  NOT_STARTED: 'NOT_STARTED',
  OVER: 'OVER'
}
